memser-spaceport/pln-directory-portal

- apps/back-office/pages/api/login.ts
> Fix: login issue

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> feat: added all events and releated guest API changes

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> fix: fixed issue in irl fetch guests by location api

- apps/web-api/src/pl-events/pl-event-locations.service.ts
> feat: introduced events ordering based on priority

- apps/web-api/prisma/migrations/20241127093907_member_signup/migration.sql
- apps/web-api/prisma/schema.prisma
> fix: fixed issue in member-signup migration

- apps/web-api/src/members/members.controller.ts
> feat: disable cache in members for testing

- apps/web-api/src/members/members.service.ts
> fix: fixed issue member type

- apps/back-office/components/member-table/member-table.tsx
> Fix: Toast message change

- apps/web-api/prisma/fixtures/members.ts
- apps/web-api/prisma/migrations/20241127093907_member_signup/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/members/members.service.ts
- libs/contracts/src/schema/member.ts
- libs/contracts/src/schema/participants-request.ts
> feat: introduced new field signUpMedium, signUpCampaign in member

- apps/back-office/components/footer-buttons/footer-buttons.tsx
- apps/back-office/components/member-table/member-table.tsx
- apps/back-office/pages/member-view.tsx
> fix: bugfixes in backoffice

- apps/web-api/src/admin/member.controller.ts
> feat(member update): added member details updation api for admin

- apps/web-api/src/admin/member.controller.ts
- apps/web-api/src/members/members.controller.ts
- apps/web-api/src/members/members.service.ts
- apps/web-api/src/utils/notification/notification.service.ts
> fix: fixed issue in sending email for member email update

- apps/back-office/components/footer-buttons/footer-buttons.tsx
- apps/back-office/components/member-table/member-table.tsx
- apps/back-office/pages/member-view.tsx
> fix: backoffice bug fixes

- apps/web-api/src/members/members.service.ts
- apps/web-api/src/utils/notification/notification.service.ts
> fix: email template mismatch when admin edits member email

- apps/back-office/pages/member-view.tsx
> fix: image url fix

- apps/web-api/src/members/members.service.ts
> fix(back office): modified team and role mapping

- apps/back-office/components/footer-buttons/footer-buttons.tsx
- apps/back-office/components/member-table/member-table.tsx
> fix: backoffice pop-up issue

- apps/web-api/src/pl-events/pl-events.controller.ts
> fix(pl-event-guest): added check condition for member team association

- apps/web-api/src/members/members.service.ts
- apps/web-api/src/participants-request/participants-request.service.ts
> fix: added cache revalidation in member, project CRUD

- apps/web-api/src/focus-areas/focus-areas.service.ts
> fix: removed unnecessary data from focus-area api

- apps/web-api/src/focus-areas/focus-areas.service.ts
> fix: removed logo details from team in focus area api

- package.json
> fix: fixed build issue in oso projects

- apps/web-api/src/teams/teams.service.ts
- apps/web-api/src/utils/cache/cache.service.ts
> fix(host filter): added isHost filter in focus-areas api

- apps/back-office/components/footer-buttons/footer-buttons.tsx
- apps/back-office/public/assets/icons/tick_green.svg
> fix: backoffice team bug fix

- apps/web-api/prisma/fixtures/members.ts
- apps/web-api/prisma/migrations/20241219130952_add_telegram_uid_unique/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/internals/internals.module.ts
- apps/web-api/src/internals/members.controller.ts
- apps/web-api/src/members/members.service.ts
- apps/web-api/src/utils/notification/notification.service.ts
- libs/contracts/src/lib/contract-internals.ts
- libs/contracts/src/schema/member.ts
> feat: added api to update telegram uid for member

- apps/web-api/src/main.ts
- apps/web-api/src/utils/forest-admin/reset-cache-after-cud.ts
- package.json
> fix: test forestadmin unblock

- apps/web-api/src/utils/cache/cache.service.ts
> fix(cache revalidation): cache revalidation for irl

- apps/web-api/src/members/members.service.ts
- apps/web-api/src/utils/cache/cache.service.ts
> fix(cache revalidation): modified cache revalidation values

- apps/web-api/src/utils/cache/cache.service.ts
> fix(cache revalidation): added revalidation tag for team airtable

- apps/web-api/prisma/fixtures/discovery-questions.ts
- apps/web-api/prisma/migrations/20250109123139_discovery_question_type/migration.sql
- apps/web-api/prisma/schema.prisma
- libs/contracts/src/schema/discovery-question.ts
> feat: introduced type in discovery questions

- .env.example
- apps/web-api/src/app.module.ts
- docker-compose.yml
> fix(redis): added seperate redis host and port for queue

- .env.example
- apps/web-api/src/app.module.ts
> fix: added QUEUE_REDIS_PASSWORD in env

- .env.example
- apps/web-api/src/app.module.ts
> fix: fixed issue in redis connection

- apps/web-api/src/app.module.ts
> fix: fixed issue home and husky api

- apps/web-api/prisma/fixtures/project.ts
- apps/web-api/prisma/fixtures/teams.ts
- apps/web-api/prisma/migrations/20250108055414_highlight_content_field/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/teams/__mocks__/teams.mocks.ts
- apps/web-api/src/teams/teams.service.ts
- libs/contracts/src/schema/project.ts
- libs/contracts/src/schema/team.ts
Reverts memser-spaceport/pln-directory-portal#2053
> Revert "feat(highlight-field): new highlight field added to Team and Project"

- apps/web-api/src/pl-events/pl-event-guests.service.ts
- apps/web-api/src/pl-events/pl-events.service.ts
> feat: reverting irl subscription and notify subscriber feature.

- apps/web-api/src/participants-request/participants-request.service.ts
> fix(date sorting): modified date and time sorting using updatedAt field

- apps/web-api/src/app.module.ts
- apps/web-api/src/members/members.service.ts
- apps/web-api/src/notifications/notifications.processor.ts
- apps/web-api/src/pl-events/pl-event-guests.service.ts
- apps/web-api/src/pl-events/pl-event-locations.service.ts
- apps/web-api/src/pl-events/pl-events.service.ts
- apps/web-api/src/utils/constants.ts
- package.json
- yarn.lock
> feat: scheduled email update for irl using cron

- apps/web-api/src/pl-events/pl-event-locations.service.ts
- apps/web-api/src/pl-events/pl-events.controller.ts
- apps/web-api/src/pl-events/pl-events.service.ts
> feat(irl-event): added email notification when admin adding new memeber

- .env.example
- apps/web-api/src/notifications/notifications.processor.ts
- apps/web-api/src/notifications/notifications.service.ts
- apps/web-api/src/pl-events/pl-event-locations.service.ts
> fix: added and processed bcc emails as batches

- apps/web-api/src/pl-events/pl-event-guests.service.ts
- apps/web-api/src/pl-events/pl-events.controller.ts
- apps/web-api/src/pl-events/pl-events.service.ts
- apps/web-api/src/utils/constants.ts
> feat(irl-event): email notification code modified

- apps/web-api/src/teams/teams.controller.ts
- apps/web-api/src/teams/teams.service.ts
Getting "something went wrong" error when we try to submit an ask using Member login (Not admin/lead)
> fix(asks): Ask Edit/add authorization logic change

- apps/back-office/components/footer-buttons/footer-buttons.tsx
500 error displayed on refreshing Back Office request detail pages & using the view links from emails received
> fix(back-office): 500 error displayed on refreshing Back Office request detail pages & using the view links from emails received

- apps/web-api/prisma/migrations/20250206124210_featured_location/migration.sql
> feat: added migration file

- apps/web-api/src/pl-events/pl-event-guests.service.ts
- apps/web-api/src/utils/cache/cache.service.ts
> fix: irl attendee filter

- apps/web-api/src/husky/husky-ai.service.ts
- apps/web-api/src/utils/constants.ts
> feat: add irl collection for husky

- apps/web-api/src/members/members.service.ts
- apps/web-api/src/teams/teams.service.ts
> feat: pl friend and lead config

- .env.example
- apps/web-api/prisma/fixtures/pl-events.ts
- apps/web-api/prisma/migrations/20250221055531_event_sync_new_fields/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/pl-events/pl-event-guests.service.ts
- apps/web-api/src/pl-events/pl-event-sync.service.ts
- apps/web-api/src/pl-events/pl-events.controller.ts
- apps/web-api/src/pl-events/pl-events.module.ts
- libs/contracts/src/lib/contract-pl-events.ts
> feat: introduced api to sync events from events service

- apps/web-api/src/pl-events/pl-event-sync.service.ts
- apps/web-api/src/utils/helper/helper.ts
> feat: added event logo sync from event service

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> fix: fixed issue in irl attendee search filter

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> Develop to staging

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> Staging to main

- apps/web-api/src/pl-events/pl-event-sync.service.ts
- apps/web-api/src/pl-events/pl-events.controller.ts
- apps/web-api/src/pl-events/pl-events.module.ts
> feat: made event sync using specific event names

- apps/web-api/src/pl-events/pl-event-sync.service.ts
> feat: added cache revalidation in irl event sync

- apps/web-api/src/teams/teams.service.ts
> feat: member addition in teams detail page

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> fix: added slug url in get attendee api

- apps/web-api/src/utils/cache/cache.service.ts
> fix: added member detail page cache revalidation in irl

- apps/web-api/src/pl-events/pl-events.controller.ts
> fix: modified guest updation check for past events

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> fix: verify guest's active membership in team

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> fix: updated topics and reason for a member across location

- apps/web-api/src/pl-events/pl-event-guests.service.ts
- apps/web-api/src/pl-events/pl-events.controller.ts
> fix: added event type in guest creation api

- apps/web-api/src/pl-events/pl-event-guests.service.ts
- apps/web-api/src/pl-events/pl-events.controller.ts
- libs/contracts/src/lib/contract-pl-events.ts
> feat: added api for fetching topics for past events

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> fix: updated members team across events

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> fix: updated office hours across events

- apps/web-api/src/pl-events/pl-event-guests.service.ts
- apps/web-api/src/pl-events/pl-events.controller.ts
- apps/web-api/src/utils/constants.ts
- libs/contracts/src/lib/contract-pl-events.ts
> feat: mark my presence

- apps/web-api/src/pl-events/pl-event-guests.service.ts
> fix: multiple mail handling

- apps/web-api/project.json
- apps/web-api/src/pl-events/pl-event-guests.service.ts
- apps/web-api/src/pl-events/pl-events.controller.ts
- apps/web-api/src/shared/markMyPresence.hbs
- apps/web-api/src/utils/aws/aws.service.ts
> feat: mail content updated with tabular column

- apps/web-api/src/shared/markMyPresence.hbs
> fix: exact link is displayed instead of View text

- apps/web-api/src/pl-events/pl-event-sync.service.ts
> fix: fixed issue in irl event resources

- apps/web-api/src/husky/husky-revalidation.service.ts
- apps/web-api/src/husky/husky.module.ts
- apps/web-api/src/members/members.module.ts
- apps/web-api/src/members/members.service.ts
- apps/web-api/src/projects/projects.module.ts
- apps/web-api/src/projects/projects.service.ts
- apps/web-api/src/teams/teams.module.ts
- apps/web-api/src/teams/teams.service.ts
- apps/web-api/src/utils/constants.ts
> feat: added revalidate api for husky

- .env.example
- README.md
- docker-compose.yml
- updated oso setup detials in readme
---
> feat: added oso database container

- apps/web-api/prisma/migrations/20250424122617_ask_status/migration.sql
- apps/web-api/prisma/migrations/20250424125939_ask_closed_fields/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/teams/teams.service.ts
Add AskStatus enum and update Ask model
- introduced AskStatus enum with OPEN and CLOSED values
- added status, closedAt, closedBy, closedReason and closedComment fields to Ask model
- updated TeamsService to handle closedAt logic
- updated TeamsService to return new details
- [Add Options to Close Asks](https://github.com/memser-spaceport/protocol-labs-directory/issues/10)
---
> feat: ask model updated with status/closedAt/closedReason columns

- apps/web-api/src/members/members.service.ts
- apps/web-api/src/projects/projects.service.ts
- apps/web-api/src/teams/teams.service.ts
> fix: made husky revalidation method to be async

- README.md
- apps/web-api/prisma/fixtures/team-member-roles.ts
- docker-compose.yml
1. Updated readme file with steps how to create a new db migration for local environment
2. Fixed seeding of the database if migrations files applied locally
3. Small fix for the "docker-compose.yml" file
- https://linear.app/magicpowered/issue/DIR-51/adding-new-db-migration-guide
---
> fix(db-migration): fixed data seed after db migration applied

- apps/web-api/src/asks/asks.controller.ts
- apps/web-api/src/asks/asks.module.ts
- apps/web-api/src/asks/asks.service.ts
- apps/web-api/src/decorators/api-body-from-zod.ts
- apps/web-api/src/projects/projects.module.ts
- apps/web-api/src/teams/teams.controller.ts
- apps/web-api/src/teams/teams.module.ts
- apps/web-api/src/teams/teams.service.ts
- libs/contracts/src/lib/contract-asks.ts
- libs/contracts/src/lib/contract-nested.ts
- libs/contracts/src/lib/contract-team.ts
- libs/contracts/src/schema/ask.ts
- Moved Asks functionality to AsksModule.
- Split Asks related endpoints:
- Get ask by id
- Create team ask
- Update ask details
- Close ask
- Delete asks
- Described asks request zod schemas.
- Temporary keep previous endpoint (`PATCH /v1/teams/:uid/ask`), added TODO to remove it after frontend integration with new endpoins is done.
---
> feat: asks refactoring

- apps/web-api/prisma/fixtures/members.ts
- apps/web-api/prisma/migrations/20250514054405_member_experience_updated_fields/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/member-experiences/member-experiences.controller.ts
- apps/web-api/src/member-experiences/member-experiences.service.ts
- libs/contracts/src/schema/member-experience.ts
> fix: updated the member experience schema

- apps/web-api/prisma/fixtures/pl-event-locations.ts
- apps/web-api/src/teams/teams.controller.ts
- apps/web-api/src/teams/teams.service.ts
fix teams page filters, add additional query params handling
---
- [x ] I've performed a self-review of my code
> fix: fix teams page filters, add additional query params handling

- docs/DATABASE_SCHEMA.md
Added MD file explaining the current ER schema
---
> feat: added docs for database schema

- apps/web-api/src/husky/tools/asks.tool.ts
- apps/web-api/src/husky/tools/husky-ai-tools.module.ts
- apps/web-api/src/husky/tools/husky-ai-tools.serivice.ts
- apps/web-api/src/husky/tools/irl-events.tool.ts
- apps/web-api/src/husky/tools/members.tool.ts
- apps/web-api/src/husky/tools/non-directory-docs.tool.ts
- apps/web-api/src/husky/tools/projects.tool.ts
- apps/web-api/src/husky/tools/teams.tool.ts
- apps/web-api/src/utils/ai-prompts.ts
- Add Non Directory Database tool to Husky
- Fix Husky tools issues
- [Connect Quadrant database to Husky](https://linear.app/plrs-labos/issue/DIR-116/connect-quadrant-database-to-husky)
---
> feat(dir-116): add non directory docs tool to husky

- apps/web-api/src/husky/tools/asks.tool.ts
- apps/web-api/src/husky/tools/focus-areas.tool.ts
- apps/web-api/src/husky/tools/irl-events.tool.ts
- apps/web-api/src/husky/tools/members.tool.ts
- apps/web-api/src/husky/tools/projects.tool.ts
- apps/web-api/src/husky/tools/teams.tool.ts
- apps/web-api/src/utils/ai-prompts.ts
- Limit Related results only to the internal links
- Remove CTA titles in related results
- [Connect Quadrant database to Husky](https://linear.app/plrs-labos/issue/DIR-116/connect-quadrant-database-to-husky)
---
> fix: standardize action links format in husky tools

- apps/web-api/src/husky/husky-ai.service.ts
- apps/web-api/src/husky/tools/non-directory-docs.tool.ts
- apps/web-api/src/utils/ai-prompts.ts
enhance non-directory docs tool to include additional action docs
- [Connect Quadrant database to Husky](https://linear.app/plrs-labos/issue/DIR-116/connect-quadrant-database-to-husky)
---
> fix: enhance non-directory docs tool to include additional action docs

- apps/web-api/src/husky/husky-ai.service.ts
- apps/web-api/src/husky/husky-chats.controller.ts
- apps/web-api/src/husky/husky.module.ts
- apps/web-api/src/husky/tools/asks.tool.ts
- apps/web-api/src/husky/tools/focus-areas.tool.ts
- apps/web-api/src/husky/tools/husky-ai-tools.module.ts
- apps/web-api/src/husky/tools/husky-ai-tools.serivice.ts
- apps/web-api/src/husky/tools/irl-events.tool.ts
- apps/web-api/src/husky/tools/members.tool.ts
- apps/web-api/src/husky/tools/non-directory-docs.tool.ts
- apps/web-api/src/husky/tools/projects.tool.ts
- apps/web-api/src/husky/tools/teams.tool.ts
- apps/web-api/src/utils/ai-prompts.ts
- libs/contracts/src/schema/husky-chat.ts
Merge to prod of Husky feature
- no ticket
---
> Husky integration

- apps/web-api/src/utils/ai-prompts.ts
Update citation requirements in husky prompt
- [Fix Husky resources minor issues](https://linear.app/plrs-labos/issue/DIR-127/fix-husky-resources-minor-issues)
---
> fix: update citation requirements in husky prompt

- apps/web-api/src/husky/husky-ai.service.ts
- apps/web-api/src/husky/husky-chats.controller.ts
- apps/web-api/src/husky/tools/husky-ai-tools.serivice.ts
- apps/web-api/src/husky/tools/members.tool.ts
Enhance contextual tools response with user login status.
- [Contact info shared with Husky (login)](https://linear.app/plrs-labos/issue/DIR-161/contact-info-shared-with-husky-login)
---
> fix: enhance contextual tools response with user login status

- apps/back-office/pages/recommendations/runs/[uid].tsx
Enhance recommendation run view with improved loading and error states
---
> feat: enhance recommendation run view with improved loading and error states

- apps/back-office/components/email-confirmation-modal.tsx
- apps/back-office/pages/recommendations/runs/[uid].tsx
- apps/back-office/pages/recommendations/runs/index.tsx
- apps/back-office/utils/constants.ts
- apps/web-api/project.json
- apps/web-api/src/admin/recommendations.controller.ts
- apps/web-api/src/recommendations/recommendations.engine.ts
- apps/web-api/src/recommendations/recommendations.service.ts
- apps/web-api/src/shared/recommendedMembers.hbs
- libs/contracts/src/schema/recommendations.ts
Add email confirmation modal and integrate email sending functionality in recommendation.
- [Send reccomendation notifications with Current Email Service](https://linear.app/plrs-labos/issue/DIR-171/send-reccomendation-notifications-with-current-email-service)
---
> Recommendations email

- apps/web-api/src/recommendations/recommendations.service.ts
- package.json
- yarn.lock
Sanitize html for member bio in recommendation email
- [Send recommendation notifications with Current Email Service](https://linear.app/plrs-labos/issue/DIR-171/send-reccomendation-notifications-with-current-email-service)
---
> Sanitize html for member bio in recommendation email

- apps/web-api/src/recommendations/recommendations.service.ts
update sanitize-html options for member bio in recommendations service
---
> fix: update sanitize-html options for member bio in recommendations service

- apps/web-api/src/auth/auth.service.ts
> fix: fixed issue in login analytics

- apps/back-office/components/navbar/navbar.tsx
- apps/back-office/components/recommendation-details-modal/recommendation-details-modal.tsx
- apps/back-office/layout/recommendations-layout.tsx
- apps/back-office/pages/recommendations/history/index.tsx
- apps/back-office/pages/recommendations/runs/[uid].tsx
- apps/back-office/pages/recommendations/runs/index.tsx
- apps/back-office/utils/constants.ts
- apps/back-office/utils/services/recommendations.ts
- apps/web-api/prisma/migrations/20250606092739_recommendation_notification/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/admin/recommendations.controller.ts
- apps/web-api/src/recommendations/recommendations.engine.ts
- apps/web-api/src/recommendations/recommendations.service.ts
Implement recommendations history and details modal
- [Recommendations Enhancements needed for the first batch of emails to be sent](https://linear.app/plrs-labos/issue/DIR-185/recommendations-enhancements-needed-for-the-first-batch-of-emails-to)
---
> feat: implement recommendations history and details modal

- apps/web-api/src/recommendations/recommendations.engine.ts
Optimize focus area, technology, and funding stage matching by removing duplicates
---
> fix: optimize focus area, technology, and funding stage matching by removing duplicates

- apps/web-api/src/recommendations/recommendations.service.ts
update recommendation email link to include target email parameter
---
> fix: update recommendation email link to include target email parameter

- apps/back-office/components/recommendation-details-modal/recommendation-details-modal.tsx
- apps/back-office/pages/recommendations/runs/[uid].tsx
- apps/back-office/utils/services/recommendations.ts
- apps/web-api/src/recommendations/recommendations.engine.ts
- apps/web-api/src/recommendations/recommendations.service.ts
- apps/web-api/src/utils/aws/aws.service.ts
Add reply to header to recommendation email. Enhance recommendation details with industry tag and improve matching logic.
- [Show Join Date in Admin Suggestions](https://linear.app/plrs-labos/issue/DIR-208/show-join-date-in-admin-suggestions)
- [Set Up Reply-to Address for Notifications Email](https://linear.app/plrs-labos/issue/DIR-202/set-up-reply-to-address-for-notifications-email)
---
> feat: add reply to, enhance recommendation details with industry tag and improve matching logic

- apps/web-api/project.json
- apps/web-api/src/participants-request/participants-request.service.ts
- apps/web-api/src/shared/onboarding.hbs
- apps/web-api/src/utils/constants.ts
- apps/web-api/src/utils/notification/notification.service.ts
implement onboarding notification email sending
- [Initiate email sending (Admin team creation)](https://linear.app/plrs-labos/issue/DIR-189/initiate-email-sending-admin-team-creation)
---
> feat: implement onboarding notification email sending

- apps/web-api/src/shared/onboarding.hbs
Update onboarding email formatting and text alignment
---
> feat: update onboarding email formatting and text alignment

- apps/web-api/src/teams/teams.service.ts
Added logs to debug an issue on prod for member removal from a team
> chore: added logs for member removal from team

- apps/back-office/components/recommendation-details-modal/recommendation-details-modal.tsx
- apps/back-office/pages/recommendations/runs/[uid].tsx
- apps/web-api/prisma/migrations/20250624190226_recommendation_example/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/project.json
- apps/web-api/src/recommendations/recommendations.engine.ts
- apps/web-api/src/recommendations/recommendations.job.ts
- apps/web-api/src/recommendations/recommendations.service.ts
- apps/web-api/src/shared/recommendedMembersExample.hbs
- apps/web-api/src/utils/ai-prompts.ts
- libs/contracts/src/schema/notification-settings.ts
- libs/contracts/src/schema/recommendations.ts
add example recommendations feature and update notification settings
- [Use LLM to generate Recommendation Explanation](https://linear.app/plrs-labos/issue/LAB-242/use-llm-to-generate-recommendation-explanation)
- [Cron Job - Recommendation Emails](https://linear.app/plrs-labos/issue/LAB-148/cron-job-recommendation-emails)
---
> feat: add example recommendations feature and update notification settings

- apps/web-api/src/recommendations/recommendations.job.ts
> fix: filter out example recommendations in recent runs of the recommendations job

- apps/web-api/src/recommendations/recommendations.engine.ts
- apps/web-api/src/recommendations/recommendations.job.ts
- apps/web-api/src/recommendations/recommendations.service.ts
> fix: enhance recommendations engine and job to support dynamic minimum score

- apps/web-api/src/recommendations/recommendations.engine.ts
> fix: update filtering logic in recommendations engine to exclude members without teams

- apps/web-api/src/shared/recommendedMembers.hbs
- apps/web-api/src/shared/recommendedMembersExample.hbs
> fix: update styles and content in recommended members email templates

- .env.example
- apps/web-api/prisma/migrations/20250626125656_linkedin_profile/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/app.module.ts
- apps/web-api/src/linkedin-verification/linkedin-verification.controller.ts
- apps/web-api/src/linkedin-verification/linkedin-verification.module.ts
- apps/web-api/src/linkedin-verification/linkedin-verification.service.ts
- apps/web-api/src/members/members.service.ts
- libs/contracts/src/schema/index.ts
- libs/contracts/src/schema/linkedin-verification.ts
implement linkedIn verification
- [Implement endpoints to connect LinkedIn](https://linear.app/plrs-labos/issue/LAB-253/implement-endpoints-to-connect-linkedin)
---
> feat: implement linkedIn verification

- apps/web-api/src/linkedin-verification/linkedin-verification.controller.ts
- apps/web-api/src/linkedin-verification/linkedin-verification.service.ts
- libs/contracts/src/schema/linkedin-verification.ts
LinkedIn callback handling and enhance error messaging
- [Implement endpoints to connect LinkedIn](https://linear.app/plrs-labos/issue/LAB-253/implement-endpoints-to-connect-linkedin)
---
> feat: streamline linkedin callback handling and enhance error messaging

- apps/web-api/src/recommendations/recommendations.controller.ts
- apps/web-api/src/recommendations/recommendations.engine.ts
- apps/web-api/src/recommendations/recommendations.module.ts
- apps/web-api/src/recommendations/recommendations.service.ts
- [Fixing issues from UAT: Recommendations (Iteration 2)](https://linear.app/plrs-labos/issue/LAB-306/fixing-issues-from-uat-recommendations-iteration-2)
---
> feat: add recommendations controller and service methods for unique roles retrieval

- apps/web-api/src/recommendations/recommendations.job.ts
> fix: update subscription status in recommendations job

- apps/web-api/src/husky/husky-generation.service.ts
- apps/web-api/src/utils/ai-prompts.ts
> fix: enhance error handling in recommendation generation

- apps/web-api/src/members/members.service.ts
- apps/web-api/src/participants-request/participants-request.controller.ts
- apps/web-api/src/projects/projects.controller.ts
- apps/web-api/src/teams/teams.controller.ts
Part of the LAB-252 task:
- sending email during user approval by admin
- sending email when admin adds a new user
- https://linear.app/plrs-labos/issue/LAB-252/create-simplified-rbac-v0-for-directory-users
> feat(lab-252): sending email when status changes from L0-L1 to L2-L4

- apps/web-api/src/members/members.service.ts
> create notification settings for new member creation (by admin)

- apps/web-api/src/home/home.controller.ts
- apps/web-api/src/projects/projects.service.ts
> fix: update fetchAllFeaturedData to use member email

- apps/web-api/src/pl-events/pl-events.controller.ts
> fix: remove access level checks for read requests in pl events

- apps/web-api/src/shared/memberApproved.hbs
- apps/web-api/src/utils/notification/notification.service.ts
> fix: update member approval email template logo

- apps/web-api/project.json
- apps/web-api/src/admin/member.service.ts
- apps/web-api/src/shared/memberRejected.hbs
- apps/web-api/src/utils/notification/notification.service.ts
> fix: add email notification for rejected users

- apps/web-api/src/member-experiences/member-experiences.service.ts
> fix: make experiences visible for users

- apps/web-api/src/auth/auth.service.ts
> feat: log email change for user in auth service

- apps/web-api/src/linkedin-verification/linkedin-verification.service.ts
> fix: add logs for linedin verification and possible fix for safari

- apps/back-office/pages/recommendations/members/index.tsx
- apps/web-api/src/recommendations/recommendations.service.ts
- apps/web-api/src/teams/teams.service.ts
> fix: enhance recommendations page to include email notifications and improve member display logic

- apps/web-api/src/shared/linkedinVerifiedAdmin.hbs
> fix: enhance linkedin verification email template

- apps/web-api/src/admin/member.service.ts
- apps/web-api/src/members/members.controller.ts
- apps/web-api/src/shared/onboarding.hbs
> fix: improve error messages and member onboarding template

- apps/web-api/src/members/onboarding-reminders.job.ts
> fix: onboarding reminder job query

- apps/web-api/src/projects/projects.controller.ts
- lambda/lambda-opensearch-sync/index.mjs
> fix: add function to delete soft-deleted projects from

- apps/web-api/src/events/events.module.ts
- apps/web-api/src/events/events.service.ts
- apps/web-api/src/members/members.service.ts
- apps/web-api/src/pl-events/pl-event-locations.service.ts
- apps/web-api/src/pl-events/pl-event-sync.service.ts
- apps/web-api/src/pl-events/pl-events.controller.ts
- libs/contracts/src/lib/contract-pl-events.ts
> fix: modified event sync to be location irrespective

- apps/web-api/src/members/members.controller.ts
- apps/web-api/src/members/members.service.ts
- libs/contracts/src/lib/contract-member.ts
> feat: add endpoint to access member details using externalId

- yarn.lock
> fix: build

- apps/web-api/src/main.ts
- apps/web-api/src/pl-events/pl-event-locations.service.ts
- apps/web-api/src/pl-events/pl-event-locations.types.ts
> fix: restricted deleted events while retrieving

- apps/web-api/src/members/members.controller.ts
- apps/web-api/src/members/members.service.ts
- libs/contracts/src/lib/contract-member.ts
- libs/contracts/src/schema/member.ts
> feat: add endpoint to retrieve members by ids

- apps/web-api/src/events/events-tooling.service.ts
> fix: added client secret header for irl event submission

- .github/workflows/prod_eks_deployment.yaml
> Adding production workflow

- apps/web-api/src/events/events-tooling.service.ts
> fix: modified event submission header

- apps/web-api/src/pl-events/pl-event-locations.service.ts
- apps/web-api/src/pl-events/pl-event-sync.service.ts
> fix: skipped event creation for virtual events

- apps/web-api/prisma/fixtures/pl-event-locations.ts
- apps/web-api/prisma/fixtures/pl-events.ts
- apps/web-api/prisma/migrations/20250805110912_priority_for_aggregated_events_locations/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/pl-events/pl-event-guests.service.ts
- apps/web-api/src/pl-events/pl-event-locations.service.ts
- apps/web-api/src/pl-events/pl-events.controller.ts
- libs/contracts/src/lib/contract-pl-events.ts
- libs/contracts/src/schema/pl-event-location.ts
- libs/contracts/src/schema/pl-event.ts
> feat: pl events location updation

- apps/web-api/src/search/search.controller.ts
- apps/web-api/src/search/search.service.ts
- libs/contracts/src/schema/global-search.ts
> Fix/lab 510/search results issue user unable to find eric ronne

- apps/web-api/src/search/search.service.ts
- lambda/lambda-opensearch-sync/index.mjs
- lambda/lambda-opensearch-sync/package.json
- lambda/lambda-opensearch-sync/yarn.lock
- libs/contracts/src/schema/global-search.ts
> feat: [Forum] Extend Global Search to Include Forum Posts and Comments

- apps/web-api/src/pl-events/pl-event-locations.service.ts
> fix: filtered location without active events

- yarn.lock
> feat: updated yarn.lock file

- apps/web-api/src/husky/husky-generation.service.ts
- package.json
- yarn.lock
Fix an error for _**v1/husky/generation/bio**_ endpoint
```
message: "Invalid input Ethiopia: 'country' must be an ISO 3166-1 code (https://en.wikipedia.org/wiki/ISO_3166-1).",
```
See [openai web search API](https://cobusgreyling.medium.com/openai-web-search-api-b24f81174305)
> Country is a two-letter ISO country code, such as US.
> Fix country code

- apps/back-office/pages/demo-days/[uid].tsx
- apps/back-office/pages/demo-days/create.tsx
- apps/back-office/pages/demo-days/index.tsx
- apps/back-office/screens/demo-days/types/demo-day.ts
- apps/web-api/prisma/migrations/20250916140816_demo_day_status_updates/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/demo-days/demo-days.service.ts
- libs/contracts/src/schema/admin-demo-day.ts
> fix: [Demo Day v1.0] Update Demo Day statuses

- apps/web-api/src/pl-events/pl-event-locations.service.ts
> fix: filtered aggregated events

- apps/web-api/src/notification-settings/notification-settings.controller.ts
- libs/contracts/src/schema/notification-settings.ts
> feat: [Demo Day v1.1] Add Investor settings

- apps/web-api/src/members/members.service.ts
* The `v1/members/autocomplete/roles` endpoint counts members, not matches
* Revert the https://github.com/memser-spaceport/pln-directory-portal/pull/2570
* Delete the `mainTeam` from the query
> Improve autocomplete roles behaviour

- apps/web-api/src/members/members.service.ts
`Fix v1/members/autocomplete/roles endpoint` to return the same count as `v1/members-search?roles`
> Count mismatches between roles and members

- apps/web-api/src/members/members.service.ts
Call `v1/members/autocomplete/roles?q=&limit=10`
**Before**
```
{
"results": [
{
"role": "Co-Founder",
"count": 257
},
{
"role": "Contributor",
"count": 238
},
{
"role": "Founder",
"count": 236
},
{
"role": "Software Engineer",
"count": 193
},
{
"role": "Co-Founder & CEO",
"count": 111
},
{
"role": "Founder & CEO",
"count": 102
},
{
"role": "Co-Founder & CTO",
"count": 54
},
{
"role": "CEO",
"count": 49
},
{
"role": "CTO",
"count": 44
},
{
"role": "Product Manager",
"count": 43
}
]
}
```
**After**
```
{
"results": [
{
"role": "Founder",
"count": 236
},
{
"role": "CEO",
"count": 49
},
{
"role": "CTO",
"count": 44
},
{
"role": "Software Engineer",
"count": 193
},
{
"role": "Product",
"count": 5
},
{
"role": "Co-Founder",
"count": 257
},
{
"role": "Contributor",
"count": 238
},
{
"role": …
```
> LAB-780 [Filters] Change default roles list

- .env.example
- apps/web-api/src/pl-events/pl-event-locations.service.ts
> feat: extend the current events window to past

- README.md
- apps/web-api/README.md
- apps/web-api/docs/DEPLOYMENT-GUIDE.md
- docs/README.md
> feat: added deployment doc

- apps/web-api/prisma/migrations/20251007151811_add_engagement_table/migration.sql
- apps/web-api/prisma/schema.prisma
- apps/web-api/src/demo-days/demo-day-engagement.service.ts
- apps/web-api/src/demo-days/demo-days.controller.ts
- apps/web-api/src/demo-days/demo-days.module.ts
```
curl --location 'http://localhost:3000/v1/demo-days/current/engagement' \
--header 'Authorization: Bearer {{USER_TOKEN}}' \
--header 'Content-Type: application/json' \
--header 'Cookie: _csrf=UqaWWTFMkWdlDAbUhLd-zg'
```
```
curl --location --globoff '{{BASE_URL}}/v1/demo-days/current/engagement/calendar-added' \
--header 'Authorization: Bearer {{USER_TOKEN}}' \
--header 'Content-Type: application/json' \
--header 'Cookie: _csrf=UqaWWTFMkWdlDAbUhLd-zg' \
--data '{}'
```
> feat: [Demo Day v2.1] Implement demo day calendar invite for investors
